config/routes.rb
Rails.application.routes.draw do

  root to: 'tasks#index'
  get 'tasks/check', to: 'tasks#check'
  resources :tasks, except: [:index]

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, :note, :completed

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks

  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  INVALID_USER_NAME_REGEX = /[\\:*;?"'$<>|]/
  validates :name, presence: true, length: { maximum: 50 },
                                    format: { without: INVALID_USER_NAME_REGEX },
                                    uniqueness: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                                    format: { with: VALID_EMAIL_REGEX },
                                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end


  def User.new_token
    SecureRandom.urlsafe_base64
  end


  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end


  def forget
    update_attribute(:remember_digest, nil)
  end


  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format.include? 'application/json' }
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def logged_in_user
    if logged_in?
      return true
    else
      flash[:danger] = "请登录！"
      redirect_to login_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :logged_in_user

  def index
    @tasks = current_user.tasks
    respond_to do |format|
      format.html { render 'index' }
      format.js { render 'remove_task'}
      format.json { render json: @tasks }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render 'new'
  end

  def create
    if email_or_username?
      @user = User.find_by(email: params[:session][:username].downcase)
    else
      temp_username = params[:session][:username].strip.gsub(/\s+/, '')
      @user = User.find_by(name: temp_username)
    end

    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_to root_path
    else
      flash[:danger] = '邮箱或者密码不正确'
      render 'new'
      flash.clear
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path
  end

  private
  def email_or_username?
    temp_name = params[:session][:username]
    if temp_name.match(/\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i)
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :logged_in_user

  def index
    @tasks = current_user.tasks
    respond_to do |format|
      format.html { render 'index' }
      format.js { render 'hide_form'}
    end
  end

  def new
    @task = Task.new
    render 'show_form'
  end

  def create
    @task = current_user.tasks.create(task_params)
    if @task.save
      @tasks = current_user.tasks
      render 'hide_form'
    else
      render 'show_form'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    @tasks = current_user.tasks
    render 'hide_form'
  end

  def edit
    @task = Task.find(params[:id])
    render 'show_form'
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      @tasks = current_user.tasks
      render 'hide_form'
    else
      render 'show_form'
    end
  end

  def check
    @task = Task.find(params[:id])
    @task.checked = !@task.checked
    if @task.save
      @tasks = current_user.tasks
      render 'hide_form'
    end
  end


  private
    def task_params
      params.require(:task).permit(:title, :note, :completed, :status)
    end

end

app/controllers/users_controller.rb
require "open-uri"
class UsersController < ApplicationController
  before_action :logged_in_user, only: :show
  def new
    @user = User.new
  end

  def show
    num = rand(5001)
    while true
      @picture = run(num)
      if @picture
        break
      else
        num = rand(5001)
      end
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
    end

    def run(num)
      base_url = "https://500px.com/photo/"
      page_url = base_url + num.to_s
      begin
        text = open(page_url).read
        pattern = /<meta content='(.*?)' property='og:image'>/
        picture_url = pattern.match(text)[1]
        if picture_url
          return picture_url
        else
          return false
        end
      rescue
        return false
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def log_in(user)
    session[:user_id] = user.id
  end


  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end


  def logged_in?
    !current_user.nil?
  end


  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end


  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end


  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_error_messages.html.erb
<% if @object.errors.any? %>
<div id="error_explanation">
    <div class="alert alert-danger">
        The form contains
        <%= pluralize(@object.errors.count, "error") %>.
    </div>
    <ul>
        <% @object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2016 <a href="http://yijiu.ren" target=_new>renyijiu</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">To Do</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" >
            <ul class="nav navbar-nav navbar-right">
                <% if logged_in? %>
                <li>
                    <%= link_to "注销", logout_path, method: "delete" %>
                </li>
            <% else %>
                <li>
                    <%= link_to "注册", signup_path %></li>
                <li>
                    <%= link_to("登录", login_path) %>
                </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag 'application' %>
        <%= javascript_include_tag 'application' %>
        <title>Todo</title>
    </head>

    <body>
        <%= render "common/navbar" %>
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12">
                    <% flash.each do |name, msg| %>
                    <%= content_tag :div, msg, class: "alert alert-#{name}" %>
                    <% end %>
                </div>
            </div>
            <%= yield %>
        </div>
        <%= render "common/footer" %>
    </body>
</html>

app/views/pages/_table.html.erb
<table class="table" id="home_table">
  <% if @tasks.empty? %>
  <span class="bg-info">
      暂时没有待做事项！
  </span>
  <% else %>
    <tr>
        <th>
            Title
        </th>
        <th>
            Note
        </th>
        <th>
            Start
        </th>
        <th>
            Deadline
        </th>
        <th>
            Category
        </th>
        <th>
            Action
        </th>
    </tr>
    <% @tasks.each do |task| %>
    <tr class=<%='checked' if task.checked %>>
        <th class='checked_th'>
            <%= task.title %>
        </th>
        <th class='checked_th'>
            <%= task.note %>
        </th>
        <th class='checked_th'>
            <%= task.created_at.strftime('%F') %>
        </th>
        <th class='checked_th'>
            <%= task.completed %>
        </th>
        <th class='checked_th'>
            <%= task.status %>
        </th>
        <th>
            <%= link_to "", { :controller => 'tasks', :action => 'check', :id => task }, class: 'glyphicon glyphicon-ok', id: 'check_button', remote: true %>&nbsp&nbsp&nbsp&nbsp
            <%= link_to "", task_path(task), method: :delete , class: "glyphicon glyphicon-remove", remote: true %>&nbsp&nbsp&nbsp&nbsp
            <%= link_to "", edit_task_path(task), class: 'glyphicon glyphicon-pencil', id: 'edit_button' %>
        </th>
    </tr>
    <% end %>
    <% end %>
</table>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
    <head>
      <h1>To Do</h1>
    </head>

    <body>
      <%= render 'table' %>
    <p>
      <%= link_to '新任务', new_task_path, class: 'btn btn-success btn-xs' %>
    </p>
    </body>
</html>

app/views/pages/remove_task.js.erb
$('#home_table').html('<%= escape_javascript(render :partial => 'table') %>');

app/views/tasks/_form.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title" id="myModalLabel">To Do</h4>
        </div>

        <%= form_for(@task, html: {class: 'form-horizontal'}, remote: true) do |t| %>

        <div class="modal-body">

            <% @object = @task %>
            <%= render 'common/error_messages' %>

            <div class="field form-group">
                <%= t.label '标题', class: 'col-sm-2 control-label' %>
                <div class="col-sm-6">
                    <%= t.text_field :title, class: "form-control", placeholder: "输入标题，不为空" %>
                </div>
            </div>
            <div class="field form-group">
                <%= t.label '事项', class: "col-sm-2 control-label" %>
                <div class="col-sm-6">
                    <%= t.text_area :note, class: "form-control", placeholder: "输入事项，不为空" %>
                </div>
            </div>
            <div class="field form-group">
                <%= t.label '完成时间', class: "col-sm-2 control-label" %>
                <div class="col-sm-6">
                    <%= t.date_field :completed, class: "input-group date" %>
                </div>
            </div>
            <div class="field form-group">
                <%= t.label '分类', class: "col-sm-2 control-label" %>
                <div class="col-sm-6">
                    <%= t.select(:status, CATEGORY) %>
                </div>
            </div>
        </div>

        <div class="modal-footer">
            <%= t.submit '保存',:class => "btn btn-success btn-sm" %>
        </div>
        <% end %>
    </div>
</div>

app/views/tasks/_table.html.erb
<table class="table" id="home_table">
  <% if @tasks.empty? %>
    <p class=<%='no_show' if !@tasks.empty? %>>
        暂时没有待办事项！
    </p>
  <% else %>
    <tr>
        <th>Title</th>
        <th>Notes</th>
        <th>Create</th>
        <th>Completed</th>
        <th>Category</th>
        <th>Action</th>
    </tr>

    <% @tasks.each do |task| %>
    <tr class=<%='checked' if task.checked %>>
        <th class='checked_th'>
            <%= task.title %>
        </th>
        <th class='checked_th'>
            <%= task.note %>
        </th>
        <th class='checked_th'>
            <%= task.created_at.strftime('%F') %>
        </th>
        <th class='checked_th'>
            <%= task.completed %>
        </th>
        <th class='checked_th'>
            <%= task.status %>
        </th>
        <th>
            <%= link_to "", { :controller => 'tasks', :action => 'check', :id => task }, class: 'glyphicon glyphicon-ok', remote: true %>
            <%= link_to "", task_path(task), method: :delete , class: "glyphicon glyphicon-remove", remote: true %>
            <%= link_to "", edit_task_path(task), class: 'glyphicon glyphicon-pencil', remote: true %>
        </th>
    </tr>
    <% end %>
  <% end %>
</table>

app/views/tasks/edit.html.erb
<!DOCTYPE html>
<% provide(:button, '更新')%>
<html>

    <body>
        <%= render 'form' %>
    </body>

</html>

app/views/tasks/hide_form.js.erb
$('#home_table').html('<%= j(render partial: 'table', locals: {tasks: @tasks}) %>');
$('#task_modal').modal('hide');

app/views/tasks/index.html.erb
<!DOCTYPE html>
<html>
    <head>
      <h1>To Do</h1>
    </head>

    <body>
      <div class="modal fade" id="task_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      </div>
      <%= render 'table' %>

    </body><br/>
    <p>
      <%= link_to '新任务', new_task_path, class: 'btn btn-success btn-xs', remote: true %>
    </p>
</html>

app/views/tasks/new.html.erb
<!DOCTYPE html>
<% provide(:button, '新建')%>
<html>

    <body>
        <%= render 'form' %>
    </body>

</html>

app/views/tasks/show.html.erb
<table class="table">
    <tr>
        <th>
            Title
        </th>
        <th>
            Notes
        </th>
        <th>
            Creates on
        </th>
        <th>
            Completed
        </th>
        <th>
            Status
        </th>
        <th>
            Action
        </th>
    </tr>
    <tr>
        <th>
            <strong><%= @task.title %></strong>
        </th>
        <th>
            <%= @task.note %>
        </th>
        <th><%= @task.created_at.strftime('%F') %></th>
        <th><%= @task.completed %></th>
        <th><%= @task.status %></th>
        <th>
            <%= link_to "删除", task_path(@task), method: :delete , data: {confirm: "Are you sure you want to delete task #{@task.title}?"}, class: 'btn btn-danger btn-xs' %>
            <%= link_to "修改", edit_task_path(@task), class: 'btn btn-info btn-xs' %>
            <%= link_to "返回", root_path, class: 'btn btn-default btn-xs'%>
        </th>
    </tr>
</table>

app/views/tasks/show_form.js.erb
$('#task_modal').html('<%= j(render partial: 'form', locals: {task: @task}) %>');
$('#task_modal').modal('show');

app/views/users/new.html.erb
<h1>
    注册
</h1>
<%= form_for(@user, url: signup_path) do |f| %>

<% @object = @user %>
<%= render 'common/error_messages' %>

<div class='form-horizontal'>

    <div class="field form-group">
        <%= f.label :name, class: 'col-sm-2 control-label' %>
        <div class="col-sm-6">
            <%= f.text_field :name, class: "form-control" %>
        </div>
    </div>
    <div class="field form-group">
        <%= f.label :email, class: "col-sm-2 control-label" %>
        <div class="col-sm-6">
            <%= f.email_field :email, class: "form-control" %>
        </div>
    </div>
    <div class="field form-group">
        <%= f.label :password, class: 'col-sm-2 control-label' %>
        <div class="col-sm-6">
            <%= f.password_field :password, class: "form-control" %>
        </div>
    </div>
    <div class="field form-group">
        <%= f.label :password_confirmation, class: "col-sm-2 control-label" %>
        <div class="col-sm-6">
            <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
            <%= f.submit "创建账户", class: "btn btn-primary" %>
        </div>
    </div>

</div>
<% end %>

app/views/users/show.html.erb
<%= image_tag @picture , alt: "彩蛋", class: "hidden_picture" %>